export const API_PATHS = {
  AUTH: {
    GOOGLE_LOGIN:    '/auth/google/login',
    CALLBACK:        '/auth/google/callback',
    GOOGLE_EXCHANGE: '/auth/google/exchange',
    REFRESH:         '/auth/refresh',
    LOGOUT:          '/auth/logout',
    ME:              '/auth/me',
  },
  BU:              '/api/bu',
  CONTI:           '/api/conti',
  CATEGORIE:       '/api/categorie',
  FORNITORI:       '/api/fornitori',
  PIANO_DEI_CONTI: '/api/piano-dei-conti',
  METODI_PAGAMENTO:'/api/metodi-pagamento',
  ALIQUOTE_IVA:    '/api/aliquote-iva',
  LOOKUP: {
    TIPI_EVENTO:    '/api/lookup/tipi-evento',
    CENTRI_DI_COSTO: '/api/lookup/centri-di-costo',
  },
  PERSONALE: {
    BASE:          '/api/personale',
    COSTO_SUMMARY: '/api/personale/costo-summary',
    MANSIONI:      '/api/personale/mansioni',
    BY_ID:         (id: string) => `/api/personale/${id}`,
  },
  MANSIONI: '/api/mansioni',
  CASSA: {
    SALDO:     '/api/cassa/saldo',
    MOVIMENTI: '/api/cassa/movimenti',
  },
  EVENTI:      '/api/eventi',
  EVENTI_MIEI: '/api/eventi/miei',
  MOVIMENTI: {
    BASE:             '/api/movimenti',
    SOMMARIO:         '/api/movimenti/sommario',
    BULK:             '/api/movimenti/bulk',
    IMPORT_CONGIUNTO: '/api/movimenti/import/congiunto',
    IMPORT_HISTORY:   '/api/movimenti/import/history',
    IMPORT_AMBIGUITA:     (logId: string) => `/api/movimenti/import/${logId}/ambiguita`,
    CLASSIFICA_AMBIGUITA: (id: string)    => `/api/movimenti/import/ambiguita/${id}/classifica`,
    IMPORT_KPI:           '/api/movimenti/import/kpi',
    IMPORT_REGOLE:        '/api/movimenti/import/regole',
    IMPORT_REGOLA_ATTIVA: (id: number)    => `/api/movimenti/import/regole/${id}/attiva`,
    IMPORT_REGOLA:        (id: number)    => `/api/movimenti/import/regole/${id}`,
    IMPORT_ROLLBACK:      (logId: string) => `/api/movimenti/import/${logId}/rollback`,
    IMPORT_TRANSITORI:            '/api/movimenti/import/transitori',
    IMPORT_TRANSITORIO_CLASSIFICA:(id: string) => `/api/movimenti/import/transitori/${id}/classifica`,
    IMPORT_EVENTI:               '/api/movimenti/import/eventi',
    IMPORT_EVENTO_RISOLVI:       (id: string) => `/api/movimenti/import/eventi/${id}/risolvi`,
    IMPORT_RICORRENTI:           '/api/movimenti/import/ricorrenti',
    IMPORT_RICORRENTE_RISOLVI:   (id: string) => `/api/movimenti/import/ricorrenti/${id}/risolvi`,
    IMPORT_TRANSITORI_RIBA:      '/api/movimenti/import/transitori/riba',
    IMPORT_QUADRATURA:           '/api/movimenti/import/quadratura',
    IMPORT_ANALISI_DUPLICATI:    '/api/movimenti/import/eventi/analisi-duplicati',
    // Feature 1 — movimenti DA_LIQUIDARE scaduti (in ritardo)
    DA_LIQUIDARE_RITARDO:        '/api/movimenti/da-liquidare-in-ritardo',
    // Feature 2 — matching differiti (riconciliazione import banche ↔ movimenti Da Liquidare)
    IMPORT_MATCHING_DIFFERITI:        '/api/movimenti/import/matching-differiti',
    IMPORT_MATCHING_DIFFERITO_RISOLVI:(id: string) => `/api/movimenti/import/matching-differiti/${id}/risolvi`,
    // Gestione Keyword (§4.8)
    KEYWORD:              '/api/movimenti/keyword',
    KEYWORD_ANTEPRIMA:    '/api/movimenti/keyword/anteprima',
    KEYWORD_ID:           (id: string) => `/api/movimenti/keyword/${id}`,
    KEYWORD_CONFLITTI:    '/api/movimenti/keyword/conflitti',
    KEYWORD_CONFLITTO_RISOLVI: (id: string) => `/api/movimenti/keyword/conflitti/${id}/risolvi`,
    NON_RICONCILIATI: '/api/movimenti/riconciliazione/non-riconciliati',
    MATCH_AUTO:       '/api/movimenti/riconciliazione/match-automatico',
    LIQUIDA:          (id: string) => `/api/movimenti/${id}/liquida`,
  },
  DASHBOARD: {
    KPI:                '/api/dashboard/kpi',
    ANDAMENTO_MENSILE:  '/api/dashboard/andamento-mensile',
    FATTURATO_PER_BU:   '/api/dashboard/fatturato-per-bu',
    ULTIME_TRANSAZIONI: '/api/dashboard/ultime-transazioni',
    SCADENZE_IMMINENTI: '/api/dashboard/scadenze-imminenti',
  },
  SPESE_RICORRENTI: {
    PIANI:          '/api/spese-ricorrenti/piani',
    PIANO:          (id: string) => `/api/spese-ricorrenti/piani/${id}`,
    LIQUIDA:        (id: string) => `/api/spese-ricorrenti/piani/${id}/liquida`,
    ANNULLA:        (id: string) => `/api/spese-ricorrenti/piani/${id}/annulla`,
    UPDATE_RATA:    (pianoId: string, rataId: string) => `/api/spese-ricorrenti/piani/${pianoId}/rate/${rataId}`,
    SKIP_RATA:      (pianoId: string, rataId: string) => `/api/spese-ricorrenti/piani/${pianoId}/rate/${rataId}/skip`,
    PAGA_RATA:      (pianoId: string, rataId: string) => `/api/spese-ricorrenti/piani/${pianoId}/rate/${rataId}/paga`,
    CONTI_COGE:          '/api/spese-ricorrenti/conti-coge',
    CONTI_COGE_INTERESSI:'/api/spese-ricorrenti/conti-coge-interessi',
  },
  REPORTING: {
    PL:                    '/api/reporting/pl',
    PL_STATUS:             '/api/reporting/pl/status',
    PL_TUTTE_BU:           '/api/reporting/pl/tutte-bu',
    CASHFLOW_STORICO:      '/api/reporting/cashflow/storico',
    CASHFLOW_FORECAST:     '/api/reporting/cashflow/forecast',
    FORECASTING:           '/api/reporting/forecasting',
  },
} as const;
