export const API_PATHS = {
  AUTH: {
    GOOGLE_LOGIN:    '/auth/google/login',
    CALLBACK:        '/auth/google/callback',
    GOOGLE_EXCHANGE: '/auth/google/exchange',
    REFRESH:         '/auth/refresh',
    LOGOUT:          '/auth/logout',
    ME:              '/auth/me',
  },
  BU:              '/api/bu',
  CONTI:           '/api/conti',
  CATEGORIE:       '/api/categorie',
  FORNITORI:       '/api/fornitori',
  PIANO_DEI_CONTI: '/api/piano-dei-conti',
  METODI_PAGAMENTO:'/api/metodi-pagamento',
  ALIQUOTE_IVA:    '/api/aliquote-iva',
  LOOKUP: {
    TIPI_EVENTO:    '/api/lookup/tipi-evento',
    CENTRI_DI_COSTO: '/api/lookup/centri-di-costo',
  },
  PERSONALE: {
    BASE:          '/api/personale',
    COSTO_SUMMARY: '/api/personale/costo-summary',
    MANSIONI:      '/api/personale/mansioni',
    BY_ID:         (id: string) => `/api/personale/${id}`,
  },
  MANSIONI: '/api/mansioni',
  CASSA: {
    SALDO:     '/api/cassa/saldo',
    MOVIMENTI: '/api/cassa/movimenti',
  },
  EVENTI:      '/api/eventi',
  EVENTI_MIEI: '/api/eventi/miei',
  MOVIMENTI: {
    BASE:             '/api/movimenti',
    BULK:             '/api/movimenti/bulk',
    NON_RICONCILIATI: '/api/movimenti/riconciliazione/non-riconciliati',
    MATCH_AUTO:       '/api/movimenti/riconciliazione/match-automatico',
  },
  DASHBOARD: {
    KPI:                '/api/dashboard/kpi',
    ANDAMENTO_MENSILE:  '/api/dashboard/andamento-mensile',
    FATTURATO_PER_BU:   '/api/dashboard/fatturato-per-bu',
    ULTIME_TRANSAZIONI: '/api/dashboard/ultime-transazioni',
    SCADENZE_IMMINENTI: '/api/dashboard/scadenze-imminenti',
  },
  SPESE_RICORRENTI: {
    PIANI:          '/api/spese-ricorrenti/piani',
    PIANO:          (id: string) => `/api/spese-ricorrenti/piani/${id}`,
    LIQUIDA:        (id: string) => `/api/spese-ricorrenti/piani/${id}/liquida`,
    ANNULLA:        (id: string) => `/api/spese-ricorrenti/piani/${id}/annulla`,
    UPDATE_RATA:    (pianoId: string, rataId: string) => `/api/spese-ricorrenti/piani/${pianoId}/rate/${rataId}`,
    SKIP_RATA:      (pianoId: string, rataId: string) => `/api/spese-ricorrenti/piani/${pianoId}/rate/${rataId}/skip`,
    PAGA_RATA:      (pianoId: string, rataId: string) => `/api/spese-ricorrenti/piani/${pianoId}/rate/${rataId}/paga`,
    CONTI_COGE:     '/api/spese-ricorrenti/conti-coge',
  },
  REPORTING: {
    PL:                    '/api/reporting/pl',
    PL_STATUS:             '/api/reporting/pl/status',
    PL_TUTTE_BU:           '/api/reporting/pl/tutte-bu',
    CASHFLOW_STORICO:      '/api/reporting/cashflow/storico',
    CASHFLOW_FORECAST:     '/api/reporting/cashflow/forecast',
    FORECASTING:           '/api/reporting/forecasting',
    EXPORT_MOVIMENTI:      '/api/reporting/export/movimenti',
    EXPORT_COMMERCIALISTA: '/api/reporting/export/commercialista',
    EXPORT_PL_BU:          '/api/reporting/export/pl-bu',
  },
} as const;
